---
development:
  cloud_name: abadfish
  api_key: '975518935329372'
  api_secret: nkikNimiBTH5kp8LI2w58hxR_c8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: abadfish
  api_key: '975518935329372'
  api_secret: nkikNimiBTH5kp8LI2w58hxR_c8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: abadfish
  api_key: '975518935329372'
  api_secret: nkikNimiBTH5kp8LI2w58hxR_c8
  enhance_image_tag: true
  static_image_support: false
