# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
user = User.create(email: "macrodynamo@gmail.com", password: "2Einsteins", role: 2)

post = Post.create(title: "The Big Short", content: "Pommy ipsum brainbox off the hook numpty had a barney with the inlaws, brainbox unhand me sir pennyboy bow ties are cool complete mare, sod's law clotted cream corgi daft cow. Copper nose rag through the dales mince pies on't goggle box Elementary my dear Watson anorak bobby mush gravy cheese and chips, bit of a Jack the lad cheesed off a week on Sunday could be a bit of a git spiffing jellied eels Moriarty what a load of guff. Dignified the black death tad Essex girls corgi stew and dumps chips, completely starkers narky pigeons in Trafalgar Square wedding tackle balderdash sod's law, I could reet fancy a bit of alright a tad a bottle of plonk lass.", summary: "Pommy ipsum brainbox off the hook numpty had a barney with the inlaws, brainbox unhand me sir pennyboy bow ties are cool complete mare.", post_date: "june 20 2016", image: "../assets/images/wmlogosymbol.png")

post_2 = Post.create(title: "The Old Man in the Tree", content: "Narky snotty nosed brat warts and all curtain twitching cotton on a week on Sunday corgi hard cheese old boy by 'eck love, knackered and thus clock round the earhole good old fashioned knees up rubbish Time Lord nosh at the boozer Dalek, Moriarty rather a tenner bloody mary old girl slappers chips. Tally-ho marmite darling crumpets a fiver bloody mary, goggledegook toad in the whole snotty nosed brat. It's spitting wind up one off you mean it ain't me noggin' working class flip flops terribly cottage pie, knee high to a grasshopper i'll be a monkey's uncle what a load of guff scally smeg head daft cow.", summary: "Narky snotty nosed brat warts and all curtain twitching cotton on a week on Sunday corgi hard cheese old boy by 'eck love, knackered and thus clock round the earhole good old fashioned knees up rubbish", post_date: "june 27 1889", image: "../assets/images/wmlogosymbol.png")

post_3 = Post.create(title: "Fancy a Cheeky?", content: "Bowler hat yorkshire mixture tallywhacker we'll be 'avin less of that fried toast for sooth eton mess, how's your father splendid clotted cream crumpets nose rag Sonic Screwdriver clock round the earhole, off with her head cheerio god save the queen queer as a clockwork orange give you a bell. Rather nose rag I could reet fancy a argy-bargy Geordie because there was nothing on the gogglebox, Amelia Pond shortbread ridicule. Nowt wellies biscuits scatterbrained scones it's spitting knee high to a grasshopper i'll be a monkey's uncle, bloody shambles superb a diamond geezer on't goggle box wedding tackle balderdash, you mean it ain't me noggin' punter Moriarty pulled a right corker beefeater.", summary: "Well fit sweet fanny adams cockney nutter rumpy pumpy Queen Elizabeth, Bob's your uncle fake tan for sooth.", post_date: "Oct 7 1774", image: "../assets/images/wmlogosymbol.png")
